[pyprland]
plugins = ["scratchpads"]
[scratchpads.term_b]
animation = "fromBottom"
# launch ncmpcpp
# command = "kitty --class kitty-dropterm_b ncmpcpp"
command = "kitty --class kitty-dropterm_b musikcube"
class = "kitty-dropterm_b"
lazy = true
size = "40% 40%"

[scratchpads.term_l]
animation = "fromLeft"
# command = "firefox https://music.apple.com"
command = "kitty --class kitty-dropterm_l"
class = "kitty-dropterm_l"
# class = "firefox"
lazy = true
size = "40% 70%"

[scratchpads.term_r]
animation = "fromRight"
command = "kitty --class kitty-dropterm_r"
class = "kitty-dropterm_r"
lazy = true
size = "40% 70%"
