[pyprland]
plugins = [
  "scratchpads",
]


[scratchpads.stb]
animation = "fromBottom"
command = "foot --class foot-stb sstb"
class = "foot-stb"
lazy = true
size = "75% 45%"

[scratchpads.stb-logs]
animation = "fromTop"
command = "foot --class foot-stb-logs stbLog"
class = "foot-stb-logs"
lazy = true
size = "75% 40%"

[scratchpads.term]
animation = "fromTop"
command = "foot --class foot-dropterm"
class = "foot-dropterm"
size = "75% 60%"
